# UNIVERSIDADE FEDERAL DO MARANHÃO
# ALGORITMOS E ESTRUTURA DE DADOS
# ALUNOS: ANTONIO LISTER AZEVEDO SOUSA, HELTON ALVES SA E VALDIMIR BARROS DE CARVALHO

from app.menuPrincipal import menuPrincipal

# ARQUIVO PRINCIPAL
print('-='*26)


print(' #######- BEM VINDO AO DESAFIO COVID - MA - AED #######')
print('-='*26)
menuPrincipal()

